### ISSUE TITLE
An argument to customise the directory of crash reproducers

### ISSUE THREAD

**Issue by Alan32Liu** [google/centipede#139]
Currently, Centipede saves all inputs that crash the target program into [`crashes/` of `workdir/`](https://github.com/google/centipede/blob/c9f0ea0458d081addc39abfbf89ac3ebd5b804cb/environment.cc#L293).
Would it be possible to add a feature to allow users to customise which directory to save those inputs?
For example, it would be great if Centipede could take a flag `--crashes-dir=</path/to/crashes>` and save crash reproducers to the dir `</path/to/crashes>` at the users' preference.
Thanks!

**Comment by kcc** [comment]
it's certainly possible, but I wont to avoid avoidable flags. :)
Is this flag avoidable?

**Comment by Alan32Liu** [comment]
Thanks!
Yep, we have a workaround for now : )
I will come back here if this turns out to be necessary later!
