### ISSUE TITLE
Creating work directory and corpus directory automatically.

### ISSUE THREAD

**Issue by Alan32Liu** [google/centipede#152]
`Centipede` [assumes the existence of `workdir` and `corpus_dir`](https://github.com/google/centipede/blob/8763fa936eee3b740eda778242a3328d52aed7d2/centipede.cc#L149).
It will exit due to a check failure if `workdir` is missing:
```
centipede.cc:149] Check failed: !!((appender->Open(env.MakeCorpusPath(shard))).ok())!=false [0!=0]
```
Or terminate with an uncaught exception if `corpus_dir` is mssing:
```
libc++abi: terminating with uncaught exception of type std::__1::__fs::filesystem::filesystem_error: filesystem error: in recursive_directory_iterator: No such file or directory ["/out/corpus_not_exist"]
```

Would it be a good idea to let `Centipede` create those two directories when they do not exist?
This will help OSS-Fuzz (and probably other users) : )
Thanks!

**Comment by ussuri** [comment]
That sounds reasonable. We'll add this feature.

**Comment by kcc** [comment]
This was a deliberate choice so that wrong dir names are not created by mistake. 
Also matches libFuzzer's behavior.

**Comment by ussuri** [comment]
So you're saying we shouldn't do this?

**Comment by kcc** [comment]
Yes.

**Comment by ussuri** [comment]
Ok, closing then.
