### ISSUE TITLE
Centipede eventually filling /dev/shm and crashing

### ISSUE THREAD

**Issue by cjb** [google/centipede#186]
Hi!  I'm running Centipede on a single machine.  I'm able to fuzz for around a day, with a large --num_runs, --batch_size=1000, and --j=12.  While the run is happening, /dev/shm grows until it reaches a large fraction of the physical RAM of the machine, and eventually dies with SIGBUS on a write to shm.  What's the best practice for avoiding this happening?  Thanks!

**Comment by kcc** [comment]
Thanks for the report. I saw exactly this last week, and had to `rm /dev/shm/*`.
You can probably workaround with a smaller shm size (`shmem_size_mb`, default is 1024), but we'll need to fix it better than that.

**Comment by kcc** [comment]
I think the main problem is fixed. Centipede can still eat up all of your RAM, but it won't eat more of `/dev/shm` than it needs to. 
The main control knobs are `--shmem_size_mb`  and `--batch_size`. 

A somewhat related problem remains: if centipede is killed externally it won't clean up after itself in `/dev/shm`. 
I am not aware of a good solution for that. (It's a different story anyway)
