### ISSUE TITLE
Would the be a chance to include *time* in the log messages?

### ISSUE THREAD

**Issue by Alan32Liu** [google/centipede#212]
`Centipede` has very informative log messages, e.g.:
```
centipede.cc:177] [74000000] new-feature: ft: 16886 cov: 717 cnt: 717 df: 17 cmp: 16152 path: 0 pair: 0 corp: 10002/10061 max/avg 998242 21191 d202/f0 exec/s: 1111.6 mb: 823
```
Would there be any chance that it could also include *how long it has been running*?
I would really appreciate that, as it could largely help us to easily identify if `Centipede` has terminated earlier than expected during evaluation.

Thanks : )

**Comment by Alan32Liu** [comment]
Here is a quick example for `libFuzzer`, hope it could help:
```
#870850783: cov: 699 ft: 3763 corp: 1674 exec/s 10057 oom/timeout/crash: 0/0/0 time: 82511s job: 423 dft_time: 0
```
It shows `time: 82511s`, implying that it has been running for ~23 hours.

I reckon this feature will also benefit other users, as many other fuzzers (e.g., `honggfuzz`, `eclipser`) print similar time information as well : )

**Comment by ussuri** [comment]
This is certainly possible. Not to say that that wouldn't be useful, or that we aren't going to add that, but aren't the recently enabled log timestamps at least partially helpful in that regard:

**I0919 04:25:55.872262**     188 centipede.cc:181] [9000] new-feature: ft: 879 cov: 31 cnt: 31 df: 0 cmp: 668 path: 0 pair: 180 corp: 342/342 fr: 0 max/avg 531 30 d0/f0 exec/s: 0 mb: 265
**I0919 04:25:55.893925**     188 centipede.cc:181] [10000] new-feature: ft: 883 cov: 31 cnt: 31 df: 0 cmp: 672 path: 0 pair: 180 corp: 344/344 fr: 0 max/avg 531 30 d0/f0 exec/s: 0 mb: 265
**I0919 04:25:55.894154**     188 centipede.cc:181] [10000] end-fuzz: ft: 883 cov: 31 cnt: 31 df: 0 cmp: 672 path: 0 pair: 180 corp: 344/344 fr: 0 max/avg 531 30 d0/f0 exec/s: 0 mb: 265

?

**Comment by Alan32Liu** [comment]
Ah yes, that is great.
I just realised that I was not using the latest version of `Centipede` in the evaluation, hence did not notice this new feature.
Testing the latest version with the benchmarks now.
Thanks!
