### ISSUE TITLE
--cxxopt=libc++ in .bazelrc?

### ISSUE THREAD

**Issue by oliverchang** [google/centipede#24]
With the OSS-Fuzz toolchain, the build complains unless we add `--cxxopt=libc++ --linkopt=-lc++` to .bazelrc.

Would it make sense to add this by default?

**Comment by kcc** [comment]
That's probably because the OSS-Fuzz environment doesn't have the default libstdc++, right? 
I don't want to make `--cxxopt=libc++ --linkopt=-lc++` the default, because there are lots of environments where it's not available. 
So, I guess, let's just use these two flags for oss-fuzz.

**Comment by oliverchang** [comment]
ack, that makes sense. we'll just set this for OSS-Fuzz.
