### ISSUE TITLE
Produce a single .a for `fuzz_target_runner`. 

### ISSUE THREAD

**Issue by oliverchang** [google/centipede#37]
Would it be possible for the current build system to produce a single `.a` for the `fuzz_target_runner` to link against fuzz targets? 

Right now we hardcode the list of `.a` files we need to link in on FuzzBench: https://github.com/google/fuzzbench/blob/199d51fdbaadbaa13161e4215196dee270cd0d1c/fuzzers/centipede/fuzzer.py#L33 which is very brittle. Globbing for all `.a` files also doesn't seem to work.

**Comment by ussuri** [comment]
Yes, it should be possible: I'm working on this now.

**Comment by ussuri** [comment]
This particular aspect of the OSS build simplification has been fixed in this PR: https://github.com/google/centipede/pull/33/commits.

What still remains: running with the fork server on is still finicky; I'm working on addressing that now (with Kostya's great inputs).

Closing this issue.
