### ISSUE TITLE
How to give valid initial seed to fuzz a binary? 

### ISSUE THREAD

**Issue by jafarsarif10** [google/centipede#404]
In the wiki it is mentioned 
**Input {#input}
A sequence of bytes that can be fed to a target. The input can be an arbitrary bag of bytes, or some structured data, e.g., serialized proto.**

Is there a mechanism to provide valid initial input to fuzz binary which centipede will mutate as it finds new coverage.

**Comment by kcc** [comment]
There are two flags for that `export_corpus_from_local_dir` and `corpus_dir`.
See https://github.com/google/centipede/blob/main/environment.cc

`corpus_dir` is there mostly for backward compatibility with libFuzzer.
If you don't need this compatibility, use export_corpus_from_local_dir:

* Create a directory `seeds` with your seed inputs, one input per file.
* Create an empty workdir `wd`.
* Run `centipede --workdir wd --export_corpus_from_local_dir seeds`
* This will create a corpus file inside wd, now you can run fuzzing
* You can inspect what's inside the corpus file with `--for_each_blob`

Example:

```
% mkdir wd seed
% echo some-data > see^C
% rm -rf wd/ seed/
% mkdir wd seeds
% echo some-data > seeds/a
% echo some-other-data > seeds/b
% ./centipede --workdir wd --export_corpus_from_local_dir seeds
I1220 09:47:13.092815  228772 centipede.cc:176] shard=0 inputs_added=2 inputs_ignored=0 num_shard_bytes=0 shard_data.size()=0 
% ls -l wd/
total 4.0K
-rw-r--r-- 1 kcc primarygroup 166 Dec 20 09:47 corpus.000000
% ./centipede --for_each_blob='cat %P' wd/corpus.000000 
I1220 09:48:31.451391  229010 centipede_interface.cc:69] Running 'cat %P' on wd/corpus.000000
some-data
some-other-data
% 
```

**Comment by kcc** [comment]
(feel free to reopen if needed)
