### ISSUE TITLE
libpng: Could not get PCTable

### ISSUE THREAD

**Issue by janphilg** [google/centipede#522]
When trying to fuzz libpng, after compiling it like descripted in [README](https://github.com/google/centipede#the-libpng-example) and with [clang-flags.txt,](https://github.com/google/centipede/blob/main/clang-flags.txt) I always get the error 
`I0302 13:38:17.196240  400288 control_flow.cc:81] Fall back to GetPcTableFromBinaryWithTracePC
 I0302 13:38:17.271314  400288 centipede_callbacks.cc:52] Could not get PCTable, exiting (override with --require_pc_table=0)`

I calling centipede with 
`centipede/bazel-bin/centipede --binary=libpng_read_fuzzer --workdir=test_fuzzers/workdir_centipede`

Did I do something wrong calling centipede that way or with the instrumentation flags of clang in clang-flags.txt? Or is a specific clang version necessary? I tried it with clang 17.0 and 12.0

**Comment by kcc** [comment]
Please try `--binary=./libpng_read_fuzzer` (note the `./`). 
If it still doesn't work, please provide the exact reproduction steps.

**Comment by janphilg** [comment]
I have the same issue using `./libpng_read_fuzzer`. 
The steps are:
`LIBPNG_BRANCH=v1.6.37`
`git clone --branch $LIBPNG_BRANCH --single-branch https://github.com/glennrp/libpng.git` 
`cd libpng`
`cp ../centipede/clang-flags.txt .`
`CC=clang`
`CFLAGS=@clang-flags.txt`
`./configure --disable-shared`
`make -j`
`clang++ -include cstdlib ./contrib/oss-fuzz/libpng_read_fuzzer.cc ./.libs/libpng16.a ../centipede/bazel-bin/libcentipede_runner.pic.a -ldl -lrt -lpthread -lz -o ../centipede/bazel-bin/libpng_read_fuzzer`
`cd ..`

Compiling libpng and linking works without error.
Clang flags are:
`-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION`
`-fno-builtin`
`-fsanitize-coverage=trace-pc-guard,pc-table,trace-cmp`
`-O2`
`-gline-tables-only`

Then I run 
`cd centipede/bazel-bin`
`./centipede --binary=./libpng_read_fuzzer --workdir=../../workdir`

Output is:
`I0303 09:08:08.917957  606056 environment.cc:323] --timeout_per_batch default wasn't overridden; auto-computed to be 1792 sec (see --help for details)
I0303 09:08:08.920457  606056 centipede_interface.cc:193] Coverage dir ../../workdir/libpng_read_fuzzer-7daf5c1541cccd099c3a8fe3d6b9b6e5de40894f
I0303 09:08:08.920588  606056 centipede_default_callbacks.cc:36] Detecting custom mutator in target...
I0303 09:08:08.920623  606056 command.cc:100] Starting fork server for ./bazel-bin/libpng_read_fuzzer
I0303 09:08:08.920667  606056 command.cc:116] Fork server command:
CENTIPEDE_FORK_SERVER_FIFO0=/tmp/centipede-606056-140037703833408/3d39f8d06cbb85644640dce7e6143db2b0cf4df9_FIFO0 \
CENTIPEDE_FORK_SERVER_FIFO1=/tmp/centipede-606056-140037703833408/3d39f8d06cbb85644640dce7e6143db2b0cf4df9_FIFO1 \
CENTIPEDE_RUNNER_FLAGS=:timeout_per_input=60:timeout_per_batch=1792:address_space_limit_mb=8192:rss_limit_mb=4096:crossover_level=50:path_level=0:use_pc_features:use_cmp_features:use_auto_dictionary:use_dataflow_features::shmem:arg1=/centipede-shm1-606056-140037703833408:arg2=/centipede-shm2-606056-140037703833408:failure_description_path=/tmp/centipede-606056-140037703833408/failure_description:: \
./bazel-bin/libpng_read_fuzzer \`
`> /tmp/centipede-606056-140037703833408/log \
2>&1 &`
`I0303 09:08:08.925994  606056 centipede_default_callbacks.cc:44] Custom mutator undetected or misbehaving: will use built-in`
`I0303 09:08:08.926030  606056 centipede_default_callbacks.cc:45] external_mutator_ran=false mutants.size()=0` 
`I0303 09:08:08.930070  606056 control_flow.cc:81] Fall back to GetPcTableFromBinaryWithTracePC`
`I0303 09:08:09.017647  606056 centipede_callbacks.cc:52] Could not get PCTable, exiting (override with --require_pc_table=0)`

**Comment by kcc** [comment]
In you instructions, `configure` does not pick up CC and CFLAGS because you didn't export them

**Comment by kcc** [comment]
`CC="clang @${PWD}/clang-flags.txt"  ./configure --disable-shared` makes things work.

```
I0303 15:46:42.986107 4023178 centipede.cc:200] [32000] new-feature: ft: 1675 cov: 101 cnt: 0 df: 0 cmp: 1574 path: 0 pair: 0 corp: 1102/1103 fr: 0 max/avg: 93/31 d0/f0 exec/s: 21654 mb: 272
I0303 15:46:43.021925 4023178 centipede.cc:200] [33000] new-feature: ft: 1688 cov: 101 cnt: 0 df: 0 cmp: 1587 path: 0 pair: 0 corp: 1115/1116 fr: 0 max/avg: 93/31 d0/f0 exec/s: 21802 mb: 272
I0303 15:46:43.067267 4023178 centipede.cc:200] [34000] new-feature: ft: 1713 cov: 101 cnt: 0 df: 0 cmp: 1612 path: 0 pair: 0 corp: 1134/1135 fr: 0 max/avg: 93/31 d0/f0 exec/s: 21810 mb: 272
I0303 15:46:43.111425 4023178 centipede.cc:200] [35000] new-feature: ft: 1723 cov: 101 cnt: 0 df: 0 cmp: 1622 path: 0 pair: 0 corp: 1142/1143 fr: 0 max/avg: 93/31 d0/f0 exec/s: 21833 mb: 272
I0303 15:46:43.158571 4023178 centipede.cc:200] [36000] new-feature: ft: 1732 cov: 101 cnt: 0 df: 0 cmp: 1631 path: 0 pair: 0 corp: 1151/1152 fr: 0 max/avg: 93/31 d0/f0 exec/s: 21815 mb: 272
I0303 15:46:43.201880 4023178 centipede.cc:200] [37000] new-feature: ft: 1741 cov: 101 cnt: 0 df: 0 cmp: 1640 path: 0 pair: 0 corp: 1160/1161 fr: 0 max/avg: 93/31 d0/f0 exec/s: 21848 mb: 272
I0303 15:46:43.246758 4023178 centipede.cc:200] [38000] new-feature: ft: 1752 cov: 101 cnt: 0 df: 0 cmp: 1651 path: 0 pair: 0 corp: 1170/1171 fr: 0 max/avg: 93/31 d0/f0 exec/s: 21859 mb: 272
```

Feel free to reopen if it still doesn't. 
Also, I'd appreciate it if you could share any other feedback with Centipede on libpng :)
