### ISSUE TITLE
May I contribute code to this repo?

### ISSUE THREAD

**Issue by Alan32Liu** [google/centipede#563]
I was wondering if there would be any chance that you could kindly allow me to create PRs for this repo?
I am planning to push 1) [a fix to keep linkopts](https://github.com/Alan32Liu/centipede/tree/keep_linkopts) and 2) [a unit test](https://github.com/Alan32Liu/centipede/tree/clusterfuzz_tests) to check if the output format can match the regex used in clusterfuzz, and I would really appreciate it if I could create PR directly : )

If that is inconvenient, I am still happy to create CLs as before (which might take me a bit more time).

Thanks!

**Comment by ussuri** [comment]
Hi Dongge,

As Kostya said in another thread, we aren't set up to easily backport PRs into our master version control. OTOH, any internal CLs that changes Centipede code base will auto-create a GitHub PR, so it's an easy workflow (internally, to be fair).

--Sergey

**Comment by Alan32Liu** [comment]
Sure, no problem.
I will submit CL to g3.
