### ISSUE TITLE
Is there a way to disable the limit on the number of runs?

### ISSUE THREAD

**Issue by Alan32Liu** [google/centipede#76]
The default value of `num_runs` (1000000000) is very large yet still insufficient for long experiments (e.g., 24 hours).
For example, `Centipede` passed that number in around 4 hours when running on benchmark `curl_fuzzer_http`.

Here are [a log file showing `Centipede` reached that number and exited when fuzzing `curl_fuzzer_http`](https://storage.googleapis.com/libfuzzer-dataflow-benchmarks/2022-07-18-10-52-24h-dongge/curl_curl_fuzzer_http-centipede/trial-2045801/results/fuzzer-log.txt) and [a csv file showing that happened in around 4 hours (14400 seconds)](https://storage.googleapis.com/libfuzzer-dataflow-benchmarks/2022-07-18-10-52-24h-dongge/data.csv) and no data was recorded afterwards.
The second file also shows this happened on almost all benchmarks within 24 hours.

A temporary solution could be increasing the value of `num_runs`, but that is not reliable, given we cannot tell how many runs will be sufficient for all benchmarks.

Would there be a way to disable this limit? Thanks!

**Comment by Alan32Liu** [comment]
Thanks! Trying out the new version now!

**Comment by kcc** [comment]
please also pick up https://github.com/google/centipede/pull/78

**Comment by Alan32Liu** [comment]
Done : )
