### ISSUE TITLE
Would there be a file to record all the dependencies in a machine readable way?

### ISSUE THREAD

**Issue by Alan32Liu** [google/centipede#80]
Recording all dependencies in a machine-readable file could be very helpful for users who always want to build and use the latest version of `Centipede` (e.g., `FuzzBench`, `OSS-FUZZ`).
For example, I just noticed that `Centipede` now requires `OpenSSL`(`libssl-dev`) to build, and [updated `FuzzBench`](https://github.com/google/fuzzbench/pull/1431/files) accordingly, I would really appreciate it if we could do that automatically : )

(I really like the way you use `clang-flags.txt` to store flags.)

**Comment by kcc** [comment]
We don't have such a file right now. 
It could be something simple, like install-dependencies-linux.sh that would apt-get, or some such. Will that work? 
Current deps that I can think of: 
  * bazel (to build centipede) 
  * -lcrypto (from openssl) to build
  * clang (to build Centipede and then to build targets)
  * llvm-symbolize / objdump (at runtime)

(fresh clang is preferred as always, so it's a special case)

BTW, yes, requiring libssl-dev is a recent change. Before that bazel would pull boringssl sources, but it appeared to be too noisy (fresh clang would reject boringssl sources)

**Comment by Alan32Liu** [comment]
> It could be something simple, like install-dependencies-linux.sh that would apt-get, or some such. Will that work?

Yes! That would be fantastic : )

That list of deps look pretty complete as well.
Just a minor question on `Clang`: I reckon we prefer `clang-15` specifically, as we need its dataflow tracing feature?

**Comment by kcc** [comment]
not sure. The instrumentation (tracing loads and stores) has been in LLVM for a while, so clang-15 will work. 

But the weak default implementations are there for just a week or so, and (citation needed) won't make it to clang-15. 
You need weak default implementations with some build systems that build not only the fuzz targets but also other binaries
and those binaries won't link w/o weak default implementations. 
I.e. most likely you will need fresh clang from trunk for tracing loads and stores. 

clang-flags.txt currently does not contain `trace-loads`
